#!/bin/sh
#  vida-userdel: sample script for deleting user

# parameters
PATH=/var/qmail/bin:/usr/local/bin:/usr/bin:/bin
export PATH

USER=$1
umask 077

cd || exit 111
if [ ! -d $USER ]; then
  echo "$USER does not exist!"
  exit 111
fi
vida-passwd -d -u $USER || exit 111
vida-assign -d -u $USER || exit 111
cd $USER || exit 111
rm -rf Maildir || exit 111
cd .. || exit 111
rmdir $USER || exit 111
echo -e "$USER was deleted\n";

exit 0;

