#!/bin/sh
#  getlog for multilog included in daemontools
#  usage: getlog dir period 
if [ -z $1 ]; then
  echo "Usage: getlog dir period" >&2
  exit 111
fi
cd "$1/log/main" || exit 111
/bin/cat @* current | /usr/local/bin/tai64ntai | \
/usr/bin/awk -v period=$2 '
  BEGIN {
    stime = systime() - period
  }
  {
    if($1 > stime) print $0;
  }
'
exit 0
