#!/bin/sh
#  /service/pop3d/run
#    Set environment variables IP and HOST.
#    If it is virtual domain, set DOMAINOWNER.
#    If it is necessary, set ALLOWPLAIN, too.
#    If it is not necessay, remove 'recordio' line.
exec 2>&1
exec envdir ./env sh -c '
  exec softlimit -d6000000 \
  tcpserver -vHR -l "$HOST" -c40 -- "$IP" 110 \
  recordio \
  qmail-popup "$HOST" checkpassword qmail-pop3d Maildir
'
